#------------------------------------------#
# Parametersセクション
#------------------------------------------#
Parameters:
  Environment:
    Type: String

#------------------------------------------#
# Resourcesセクション
#------------------------------------------#
Resources:
  #------------------------------------------#
  #VPC
  #------------------------------------------#
  TutorailVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: cfn-cicd
        - Key: Environment
          Value: !Sub ${Environment}
